# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: >
  Hi there, thank you for taking the time to open this issue.
  However, could you give more information about it? Please be as much as specific. Thank you!

requestInfoLabelToAdd: more-info-needed
